### PR TITLE
Updated Liquidsoap to official 1.4.3 release

### PR DESCRIPTION
**Pull request by bjarn**
https://github.com/savonet/liquidsoap/releases/tag/v1.4.3

### CODE REVIEW

**Comment by SlvrEagle23** [comment]
@bjarn If we're moving to an official release, we should probably avoid the pinning mechanism altogether and comment it out.

**Comment by bjarn** [comment]
Good point. Just tried to do that, however, compilation seems to fail with using the official way:
```
[ERROR] The compilation of liquidsoap failed at "/usr/bin/make".

#=== ERROR while compiling liquidsoap.1.4.3 ===================================#
# context              2.0.5 | linux/x86_64 | ocaml-system.4.08.1 | https://opam.ocaml.org#114ada7d
# path                 ~/.opam/ocaml-system.4.08.1/.opam-switch/build/liquidsoap.1.4.3
# command              /usr/bin/make
# exit-code            2
# env-file             ~/.opam/log/liquidsoap-7-f93c11.env
# output-file          ~/.opam/log/liquidsoap-7-f93c11.out
### output ###
# [...]
# OCAMLOPT -c decoder/external_decoder.ml
# OCAMLOPT -c decoder/raw_audio_decoder.ml
# OCAMLOPT -c decoder/ffmpeg_decoder.ml
# File "decoder/ffmpeg_decoder.ml", line 113, characters 14-37:
# 113 |         match FFmpeg.Avutil.frame_pts frame with
#                     ^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value FFmpeg.Avutil.frame_pts
# make[2]: *** [../Makefile.rules:125: decoder/ffmpeg_decoder.cmx] Error 2
# make[2]: Leaving directory '/var/azuracast/.opam/ocaml-system.4.08.1/.opam-switch/build/liquidsoap.1.4.3/src'
# make[1]: *** [../Makefile.rules:67: all-auto-ocaml-prog] Error 2
# make[1]: Leaving directory '/var/azuracast/.opam/ocaml-system.4.08.1/.opam-switch/build/liquidsoap.1.4.3/src'
# make: *** [Makefile.rules:27: all-subdirs] Error 2
```

Will look into it later or ask a developer of Liquidsoap to see if they spot the issue here.

**Comment by SlvrEagle23** [comment]
@bjarn On my end I'm not seeing `liquidsoap.1.4.3` as available on OPAM yet. May be worth waiting a bit, unless there are some important fixes in the more recent commits.

**Comment by bjarn** [comment]
After updating the ffmpeg plugin to `0.4.3`, the issue has been resolved.

**Comment by SlvrEagle23** [comment]
@bjarn If you don't have a pinned version you should use `liquidsoap.1.4.3` to ensure it's installing that version explicitly; I'm not seeing that available via OPAM yet so it may be installing 1.4.2 right now.

**Comment by bjarn** [comment]
@SlvrEagle23 will pin the version to be 100% sure. I do see however it is available:
http://opam.ocaml.org/packages/liquidsoap/liquidsoap.1.4.3/

**Pull request merged**
